const moduloA = require("./modulo-a")
const moduloB = require("./modulo-b")

console.log(moduloA.ola)
console.log(moduloA.bemVindo)
console.log(moduloA.ateLogo)
console.log(moduloA)
console.log()
console.log(moduloB.bomDia)
console.log(moduloB.boaNoite())
console.log(moduloB)